DROP TABLE IF EXISTS PRICES;
DROP TABLE IF EXISTS BRAND;

CREATE TABLE PRICES
  (
     PRICE_ID    INT PRIMARY KEY,
     BRAND_ID    INT NOT NULL,
     START_DATE  TIMESTAMP NOT NULL,
     END_DATE    TIMESTAMP NOT NULL,
     PRICE_LIST  INT NOT NULL,
     PRODUCT_ID  INT NOT NULL,
     PRIORITY_ID INT NOT NULL,
     PRICE       FLOAT NOT NULL,
     CURR        VARCHAR NOT NULL
  );

  CREATE TABLE BRAND
    (
       BRAND_ID   INT PRIMARY KEY,
       BRAND_NAME VARCHAR NOT NULL
    );